version: '3.4'

x-healthcheck: &healthcheck
  test: [ "CMD", "curl", "-sf", "http://localhost:8545" ]
  interval: 5s
  timeout: 5s
  retries: 3
  start_period: 30s

services:
  dtl:
#    build:
#      context: ..
#      dockerfile: ./ops/docker/Dockerfile.packages
#      target: data-transport-layer
    image: mantlenetworkio/data-transport-layer:${DOCKER_TAG_DATA_TRANSPORT_LAYER:-latest}
    # override with the dtl script and the env vars required for it
    entrypoint: ./dtl.sh
    env_file:
      - ./goerli/envs/dtl.env
    # set the rest of the env vars for the network which do not
    # depend on the docker-compose setup
    volumes:
      - ./data/dtl:/db
    environment:
      # used for setting the address manager address
      # connect to the 2 layers
      URL: https://mantlenetworkio.github.io/networks/goerli/addresses.json
      DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT: https://eth-goerli.g.alchemy.com/v2/xVtyd3CSQCnWyS5nt6bDPFplQZOWSbA5
      DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT: https://rpc.testnet.mantle.xyz
      DATA_TRANSPORT_LAYER__SYNC_FROM_L2: 'true'
      DATA_TRANSPORT_LAYER__L2_CHAIN_ID: 5001
    ports:
      - ${DTL_PORT:-7878}:7878

  verifier:
    depends_on:
      - dtl
    # deploy:
    #   replicas: 1
#    build:
#      context: ..
#      dockerfile: ./l2geth/Dockerfile
    image: mantlenetworkio/l2geth:0.7.2
    entrypoint: sh ./geth.sh
    env_file:
      - ./goerli/envs/geth.env
    volumes:
      - ./data/verifier:/root/.ethereum/geth/
      # - ./password:/root/.ethereum/geth/password
    environment:
      ETH1_HTTP: https://eth-goerli.g.alchemy.com/v2/xVtyd3CSQCnWyS5nt6bDPFplQZOWSbA5
      SEQUENCER_CLIENT_HTTP: https://rpc.testnet.mantle.xyz
      ROLLUP_STATE_DUMP_PATH: https://mantlenetworkio.github.io/networks/goerli/genesis.json
      ROLLUP_CLIENT_HTTP: http://dtl:7878
      ROLLUP_BACKEND: 'l2'
      ETH1_CTC_DEPLOYMENT_HEIGHT: 8
      RETRIES: 60
      ROLLUP_VERIFIER_ENABLE: 'true'
    ports:
      - ${VERIFIER_HTTP_PORT:-8547}:8545
      - ${VERIFIER_WS_PORT:-8548}:8546
      - 30303:30303